### ISSUE TITLE
Authenticating with X.509 client certificates with Symfony

### ISSUE THREAD

**Issue by santos-agudo** [veewee/veewee.github.io#1]
I don't know if you have enough time to resolve a problema that it makes me crazy and I do unable to find  a solution. The thing is I can't find a detailed example for authenticating x.509 client certicates. 

I really follwed your blog's article  and it doesn't work. Apart from your article, do you know another information source where I can find something about this topic??

I don't understand why Nobody tells about this topic, maybe it's so easy that it does't deserve to talk about it?? or, I am so clumsy.

Can you help please??

**Comment by veewee** [comment]
It isn't an easy topic and that is probably why you won't find a lot of information in the internet.
We spend a full day with 2 persons to get this working...

Can you explain to me what isn't working? Maybe I can help you out!

Here are some additional resources we used:
- https://gist.github.com/mtigas/952344
- http://nategood.com/client-side-certificate-authentication-in-ngi
- http://grahamc.com/blog/openssl-madness-how-to-create-keys-certificate-signing-requests-authorities-and-pem-files/

Note that none of the above contain the perfect solution.

**Comment by santos-agudo** [comment]
Many thanks for answering so soon. The problem I've got is when It's supposed Symfony has to take the control when the browser sends certificate information to symfony. Symfony always gives an error by saying something like "There's no token in tokestorage". My problem is the provider (or anything else) and it seems I don't know how to link browser with it. 

I got the browser selected the certificate but after that symfony doesn't recieve the data. I've read a lot of information.

Anyway, thanks a lot. There aren't many people like you by worriying about others.

Thanks.

**Comment by veewee** [comment]
Hi @santos-agudo,

For adding the certificate to your browser, there is an additional step I did not mention in the blog post:

Client certificates in your browser  will require a pkcs12 certificate, which can be easily generated with following command:

``` sh
openssl pkcs12 -export -clcerts -in client.crt -inkey client.key -out client.p12
```

Next the certificate needs to be added to the browser:

For example in firefox: 
Browse to: `about:preferences#advanced`
Click on: certificates
Click on: View certificates
Here you can now import the p12 key

When you surf to the domain for which you specified the certificate, you will be authenticated automatically.

It will also be possible to authenticate with another authentication mechanism like basic auth when the client certificate is not available.

Normally this should work fine! 
If you are still experiencing issues, you might want to debug the `Symfony\Component\Security\Http\Firewall\X509AuthenticationListener` class and dump the SERVER variables. The email in the SERVER variables should be the same as the specified user name in your user provider.

**Comment by santos-agudo** [comment]
I'm very grateful for your help. I'll follow your ideas and as soon as I get it I'll tell your.
If ever I can help you in anyway, I'll be glad to help you.

Thanks a lot.

**Comment by veewee** [comment]
Hi @santos-agudo,
Did you find a solution for your problem and Can I close this issue?
Feel free to provide some additional information so that I can update the article.

Thanks!
