### ISSUE TITLE
composer require php-soap/psr18-wsse-middleware

### ISSUE THREAD

**Issue by jcav2** [veewee/veewee.github.io#12]
Hi my friend i try install this in php 8.1.6 in windows and ubuntu. I get same error in both:

C:\xampp\htdocs\DSUtil\php\psr18-wsse>composer require php-soap/psr18-wsse-middleware
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been created
Running composer update php-soap/psr18-wsse-middleware
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-soap/psr18-transport[v1.0.0, ..., 1.2.1] require psr/http-client-implementation ^1.0 -> could not be found in any version, but the following packages provide it:
      - guzzlehttp/guzzle Guzzle is a PHP HTTP client library
      - symfony/http-client Provides powerful methods to fetch HTTP resources synchronously or asynchronously
      - php-http/guzzle6-adapter Guzzle 6 HTTP Adapter
      - symfony/symfony The Symfony PHP framework
      - php-http/curl-client PSR-18 and HTTPlug Async client with cURL
      - php-http/guzzle7-adapter Guzzle 7 HTTP Adapter
      - kriswallsmith/buzz Lightweight HTTP client
      - typo3/cms-core TYPO3 CMS Core
      - php-http/mock-client Mock HTTP client
      - php-http/socket-client Socket client for PHP-HTTP
      - php-http/guzzle5-adapter Guzzle 5 HTTP Adapter
      - multisafepay/magento2-core MultiSafepay core module for Magento 2
      - voku/httpful A Readable, Chainable, REST friendly, PHP HTTP Client
      - mjelamanov/psr18-guzzle A PSR-18 adapter for guzzle 6 client
      - ricardofiorani/guzzle-psr18-adapter A Guzzle PSR-18 adapter
      - typo3/cms TYPO3 CMS is a free open source Content Management Framework initially created by Kasper Skaarhoj an
      - juststeveking/http-slim A slim psr compliant http client to provide better interoperability.
      - code-tool/socket-client Socket client for PHP-HTTP
      - windwalker/http Windwalker Http package
      - prestashop/module-lib-guzzle-adapter Plug modules to the Guzzle client available on a running shop
      ... and 63 more.
      Consider requiring one of these to satisfy the psr/http-client-implementation requirement.
    - php-soap/psr18-wsse-middleware v1.1.0 requires php-soap/psr18-transport ^1.0 -> satisfiable by php-soap/psr18-transport[v1.0.0, v1.1.0, v1.2.0, 1.2.1].
    - Root composer.json requires php-soap/psr18-wsse-middleware 1.1.0 -> satisfiable by php-soap/psr18-wsse-middleware[v1.1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

C:\xampp\htdocs\DSUtil\php\psr18-wsse>

Thanks for your valuable help, Juan.

**Comment by veewee** [comment]
Saw somewhere that you found the solution to this issue. (install all psr specific implementations first)
Feel free to reopen the issue in the correct github project.
