### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by grosch** [veewee/veewee.github.io#2]
Hi.  I just read your article on Authenticating with X.509 client certificates.  I followed your steps and downloaded the client.pem file to my client.  Now I'm just trying to test it out from the command line so on curl I'm giving -k and -E and then the pem file, but I'm getting an unknown ca error at that point.

Thoughts?

**Comment by grosch** [comment]
OK, I made a bit of progress. It's now just failing with an alert handshake.  

I'm assuming that, since the site is using TLS v1.2 that I have to generate the certificates differently?  Sorry if this is really obvious, I'm new to this SSL configuration stuff for apache.

% curl -v -k --cacert client.pem --tlsv1.2 'https://....'
-   Trying a.b.c.d...
- Connected to ... (#0)
- ALPN, offering h2
- ALPN, offering http/1.1
- Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
- error setting certificate verify locations, continuing anyway:
-   CAfile: client.pem
  CApath: none
- TLSv1.2 (OUT), TLS header, Certificate Status (22):
- TLSv1.2 (OUT), TLS handshake, Client hello (1):
- TLSv1.2 (IN), TLS handshake, Server hello (2):
- TLSv1.2 (IN), TLS handshake, Certificate (11):
- TLSv1.2 (IN), TLS handshake, Server key exchange (12):
- TLSv1.2 (IN), TLS handshake, Request CERT (13):
- TLSv1.2 (IN), TLS handshake, Server finished (14):
- TLSv1.2 (OUT), TLS handshake, Certificate (11):
- TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
- TLSv1.2 (OUT), TLS change cipher, Client hello (1):
- TLSv1.2 (OUT), TLS handshake, Finished (20):
- TLSv1.2 (IN), TLS alert, Server hello (2):
- error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
- Closing connection 0

curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

**Comment by veewee** [comment]
It looks like the server has decided to choose TLS v1.2. See the "Server hello" rule.

`ssl3_read_bytes` and `ssl3_writes_bytes` deal with SSL3-style frames. These are the same with later versions, i.e. TLS1.x. Thus the same functions get used, even though their names might suggest a different thing.

In the command you pasted, you  are passing the client certificate with the `-cafile` parameter, but it should be passed with the `-cert` option:

```
curl -v -k --cert client.pem --tlsv1.2 'https://....'
```

This might cause the exception. The CA file can be used if you want to trust one specific server. 
As you can see you are using the -k option. You might want to download the CA file with this command:

```
openssl s_client -showcerts -connect my.host.com:443 > ca-file.pem
```

Now you can use curl as followed:

```
curl -v --cafile ca-file.pem --cert client.pem --tlsv1.2 'https://....'
```

(So with the valid CA file and without the insecure option)

You might also want to debug the SSL part with the `openssl s_client` command.

```
openssl s_client -debug -certform client.pem -CAfile ca-file.pem -tls1_2 -connect your.host:443
```

Small remark: the client certificate can also be signed on the server and be transfered to the client. This is a small error on the page.
Can you let me know if this works for you so I can update the article?

Thanks!

**Comment by grosch** [comment]
If I change it to --cert then I get this:  

> curl: (58) could not load PEM client certificate, OpenSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?)

% head -1 client.pem 
-----BEGIN RSA PRIVATE KEY-----
% wc -l client.pem 
      51 client.pem

If I run the first openssl command you give me I get this output:

> CONNECTED(00000003)
> 11525:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.40.2/src/ssl/s23_lib.c:185:

I did in fact create/sign the client.pem on the server and then transfer it to my client.  This is what my VirtualHost entry looks like:

```
SSLEngine on
SSLProtocol +TLSv1.1 +TLSv1.2
SSLCertificateFile /etc/certificates/wildcard._domainnameremoved_.com.crt
SSLCertificateKeyFile /etc/certificates/wildcard._domainnameremoved_.com.key

# This one is signed by a public certificate authority
SSLCertificateChainFile /etc/certificates/rapidSHA2_2016.crt

# This one is the private CA used to issue client certificates based on Veewee's article
SSLCACertificateFile /etc/ssl/certs/dtsAppSigner.crt

SSLVerifyClient require
SSLVerifyDepth 1
```

**Comment by veewee** [comment]
Did you provide a password to the certificate file? Then you'll have to add  `--key` to the curl command.
About the openssl command, you'll probably have to add the `-tls1_2` option.
The apache configuration looks just fine.

Do you run curl on Mac? Make sure that curl uses openssl, the default implementation has some issues with client certificates.

```
brew install curl --with-openssl
# Run this to configure PHP with the valid curl if you are using php locally
# brew install php56 --with-homebrew-curl 
echo "alias curl /usr/local/opt/curl/bin/curl" > .zshrc
```

More info: http://stackoverflow.com/questions/22305600/write-permissions-error-osstatus-61-when-reading-p12-certificate-on-osx

**Comment by grosch** [comment]
OK, I recreated a new client.pem to show my exact steps and now it's working.  So clearly I fumblefingered something there :)

When I run the openssl command with the -tls1_2 it spits out a bunch of stuff, but also dumps this to stderr:

> 140735215845456:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:s3_pkt.c:1472:SSL alert number 40
> 140735215845456:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:

Exact same thing with the openssl debug command you gave me.  TONS out output, but also those two errors.

You said that I could use the --cafile command with curl but my curl (7.49.1) doesn't have a --cafile parameter.

**Comment by grosch** [comment]
I think you might have meant --cacert?  That gives:

> curl: (60) SSL certificate problem: unable to get issuer certificate

**Comment by veewee** [comment]
Good to hear you got it working!

Yes I did mean `--cacert`. Did you manage to download the CA file with the openssl command?
Does it works with the `-k` option?

**Comment by grosch** [comment]
When I try to download into ca-file.pem I get those two errors I show, above, regarding the ssl3 stuff.  There are 105 lines output into the ca-file.pem, but if I try to use it on the curl command then I get that "curl: (60)" error I showed.

It does work with the -k option, yes.  But when I move this to production I'll need to have it not be untrusted.

**Comment by veewee** [comment]
When you run it on production without a self-signed certificate it will be marked as trusted by default. This cafile is needed to test without the -k option. You probably get the error because the exceptions you get while downloading. Not sure what goes wrong there... Do you get the error before the protocol is discussed or after? (Server hello)

**Comment by grosch** [comment]
You mean from the curl command?  

> - ALPN, offering h2
> - ALPN, offering http/1.1
> - Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> - successfully set certificate verify locations:
> -   CAfile: ca-file.pem
>   CApath: none
> - TLSv1.2 (OUT), TLS header, Certificate Status (22):
>   } [5 bytes data]
> - TLSv1.2 (OUT), TLS handshake, Client hello (1):
>   } [512 bytes data]
> - TLSv1.2 (IN), TLS handshake, Server hello (2):
>   { [113 bytes data]
> - TLSv1.2 (IN), TLS handshake, Certificate (11):
>   { [2792 bytes data]
> - TLSv1.2 (OUT), TLS alert, Server hello (2):
>   } [2 bytes data]
> - SSL certificate problem: unable to get issuer certificate
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> - Closing connection 0
>   } [5 bytes data]
> - TLSv1.2 (OUT), TLS alert, Client hello (1):
>   } [2 bytes data]
>   curl: (60) SSL certificate problem: unable to get issuer certificate

**Comment by veewee** [comment]
I see you've added following configuration:

```
SSLCertificateFile /etc/certificates/wildcard._domainnameremoved_.com.crt
SSLCertificateKeyFile /etc/certificates/wildcard._domainnameremoved_.com.key
SSLCertificateChainFile /etc/certificates/rapidSHA2_2016.crt
```

This means it is a signed certificate? Normally you shouldn't get any errors unless you are trying to reach a domain that is not in the wildcarded domain?
I think this is triggering the error: you are using a wrong certificate for the domain you are testing. 
That is why the `-showcerts` cant create a full CA tree.

Good to know: 

> The way openssl works is it tries to complete the certificate chain during verification.
> Is your server certificate signed by an intermediate CA and not a root CA. For example if your certificate chain is server_cert, signed by intermediate_cert, signed by rootCA you will get errors if openssl cannot for the entire chain. The way openssl works is it tries to form a complete certificate chain (server cert to root CA) during verification. If the server does not provide the intermediate CA certs, openssl looks it up in the certificate store. If it cant it will throw an unknown CA error.

http://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by grosch** [comment]
The ones you showed there are certificates provided by a signing authority, not self-signed.  It looks like all I have to do is leave the '-k' off the curl command and then it works fine.  I don't need to download the ca-file.pem because the keys from above validate the server.

The one part I'm not clear here though is how this really provides protection.  That client.pem file has to be readable by anyone, meaning that if I'm on that client system I can grab a copy of the key and then connect to the server from any machine I want, simply by copying the file to my local box.

**Comment by veewee** [comment]
That is correct, I did not notice it was signed by an authority at first. In that case you won't need a cafile since it is already known by the root CAs.

About the security:

You are correct: if the client computer gets hacked and the certificate gets stolen, then the hacker will have access to your system. However, this is the same with a regular password. If the hacker gets access to a database with regular usernames / password it's not safe either.
The client key you generated contains a private key. The client is responsible for keeping it private.
The certificates protect against 2 types of security threaths:

> The certificate protects users against the most common authentication security threat: password reuse. Most internet users have a tendency to use the same or similar passwords across different sites, even banking sites. When this occurs, it means the compromise of a password database from another site now allows access to the banking site.
> 
> Certificates also protect against the 2nd most common threat: phishing. Using mutual authentication in TLS for the client verification makes phishing almost impossible. (The attacker would need to plant a rogue CA in both sides of the connection, and if they're in a position to do that, they can do many worse things.)
> 
> You are correct that a certificate is not significantly harder for an attacker to steal than credentials, so offers little security to a user with a compromised endpoint. The certificate does protect against two very real problems, however, and is thus a more secure option than a simple username/password. As you've pointed out, this security comes with a usability cost, which is unfortunate.

Source: http://security.stackexchange.com/questions/61810/are-login-certificates-more-secure-than-standard-username-password-authentic

As mentioned above, the certificates come with a usibility cost. It is possible to let users sign in with a PKCS 12 certificate. Most users won't even know where to start doing this. They don't know what PKCS 12 is and how to import the key into their browser. Even if so: they won't understand why there is no logout button.

To generate this certificate:

```
openssl pkcs12 -export -clcerts -in client.crt -inkey client.key -out client.p12
```

This is why we don't use this to protect web applications. Where we DO use this technique for, is for the protection of API's. We've got a lot of automation APIs on applications which can be triggered from a client on our build server. So when we need to build X applications, we just trigger the right API with the right client. This client takes the pem file as a source so that the server knows which applciation is connecting. It can also be used for regular API implementations, since the only thing you'll need to do is add the certtificate. You won't care about usernames and passwords anymore.

Besides the points above, there are still some additional things you can do to make it more secure:

You can add a key to the client certificate. When you want to use the pem file, you'll also have to add the key to make the client certificate usable. This can be a hassle so we currently don't do that.

You can set the expiration date of the certificate rather low and rotate the client keys quickly. Also the Certificate Authority certificate has an expiration date. These are things you can play with.

Since openssl keeps a copy of it's signed certificates, It is possible to revoke certificates with one of the following commands:

```
openssl ca -revoke /etc/ssl/newcerts/1013.pem #replacing the serial number
openssl ca -revoke bad_crt_file -keyfile ca_key -cert ca_crt
```

More info: http://stackoverflow.com/questions/9496698/how-to-revoke-an-openssl-certificate-when-you-dont-have-the-certificate

You might want to move these signed certificates to a more secure location.
In the worst case: When a hacker gets access to your server and steals all the signed keys, you can still create a new CA file or revoke all certificates and generate new client certificates.

All the steps above can be automated in some kind of dashboard if it seems too much manual work.
For example: PHP has a wrapper for almost all openssl commands: http://php.net/manual/en/book.openssl.php. This means you could let the users manage their own certificates but let moderators manually revoke users etc.

I hope the information above gives you a more confident feeling for using SSL client certificates to protect your application.

**Comment by grosch** [comment]
> This is why we don't use this to protect web applications. Where we DO use this technique for, is for the protection of API's. We've got a lot of automation APIs on

Any chance of you doing a blog post on this?  This is exactly what I’m doing…securing an API. 

> You might want to move these signed certificates to a more secure location.
> 
> It just occurred to me that the certificates don’t need to be public, they can just be set to only be readable by the webserver process, since that’s who ‘reads’ the certificate in the first place, right?  

I’m still trying to figure out how to add this key to Chrome on my mac so that I can go to these URL’s.  I opened up the Keychain Access app and added this to the login keychain under the certificates category.  I see it there but Chrome isn’t actually using it.

Really appreciate all the great info you’re sharing here!

**Comment by veewee** [comment]
I do plan to write some more on the topic, but currently I am a bit busy with some other side projects. Maybe later :)

It is indeed possible to give only read access to the user who is using the certificate on the machine. This will also protect the resource a bit more. Good point!

About importing in chrome:
First you'll need to create a pkcs12 certificate:

```
openssl pkcs12 -export -clcerts -in client.crt -inkey client.key -out client.p12
```

Next you'll need to add it to chrome:
- Browse to: chrome://settings/search#ssl
- Click manage certificates
- Add it to the keychain.

Now that you configured chrome, you will have to make sure that the certificate is authorized in your application. I assume you are using apache / php  for now. Probably in other software it will work in a similar way:

These options should be in apache

``` sh
# Verify the client certificate: Optional if you want to support multiple authentication types or unauthenticated users, require if you require a client certificate as the only authentication option.
SSLVerifyClient optional 

# The verification depth. Keep this at 1 as you want to validate it against the CA specified in SSLCACertificateFile.
SSLVerifyDepth 1

# This will add the SSL_ environment variables to the request.
SSLOptions +StdEnvVars
```

The last variable `SSLOptions` is critical. This will allow you to access the SSL identity in your script:

``` php
<?php
$email = $_SERVER['SSL_CLIENT_S_DN_Email'];
if (!$email && preg_match('#/emailAddress=(.+\@.+\..+)(/|$)#', $_SERVER['SSL_CLIENT_S_DN'], $matches)) {
    $email = $matches[1]
}
```

**NOTE:**  The SSL_ environment variables are only available when browsing over HTTPS. Make sure to enforce HTTPS!!!!!

As you can see, the code above reads the DN_Email part of the client certificate and this value will specify be the identity of your application. Now you can match this email to a user in your application. 

The code pasted above, you can also find in the Symfony authentication x509 provider:
https://github.com/symfony/security/blob/master/Http/Firewall/X509AuthenticationListener.php
So if you are using Symfony as framework, you can just:

``` yaml
security:
    providers:
        client_certificate:
            memory:
                users:
                    email@certification.file:
                      roles: ROLE_SUPER_ADMIN

    firewalls:
        main:
            x509:
                provider: client_certificate

    access_control:
            - { path: ^/, roles: ROLE_SUPER_ADMIN, requires_channel: https }

```

**NOTE:**  This snippet is enforcing https in the access_control part. You can also do this on Apache level!!!

Finally: Authorization is handled by your application. The email is matched to a user and you can look up the roles / permissions of a user in the application.

**Comment by grosch** [comment]
Thanks.  I scripted the generation of the .pem  and .p12 files now so that I don’t forget how this works :)

> # This will add the SSL_ environment variables to the request.
> 
> SSLOptions +StdEnvVars
> The last variable SSLOptions is critical. This will allow you to access the SSL identity in your script:
> 
> Not really sure why you’re doing this.   The cert was generated for a VirtualHost and so by virtue of the connection happening we know what application is was linked against.  I set the SSLVerifyClient to required, not optional, because you MUST have the key to connect. 

If you start adding in an email address, aren’t you then just going back to having a key per person, instead of a key per machine?

**Comment by veewee** [comment]
The SSLOptions are added to identify the machine. The email could be something like machine1@yourdomain.com. This way you can handle authorization in your application.
Otherwise you've got a key but don't know the identity of the key and you won't be able to set permissions per machine.
You can add the serial of the user to the database to make it easier to revoke the client certificate.

It's not necessary, but it's a recommended part :)

**Comment by grosch** [comment]
> Otherwise you've got a key but don't know the identity of the key and you won't be able to set permissions per machine.

OK, understood.  I’m my case I’m not setting per machine, it’s just “Can I access this API” and everyone in the client’s company can run the app.  I’m going to _also_ turn on basic authentication (I hope it works with this….) so that I can do authorization levels.  I don’t want a case where the boss walks away from his box, Billy runs over and runs the app and is admin because he’s on that host.  

I want him to still give a user/pwd when he connects and let the server side determine what rights he has.  

But doing this still prevents people from outside the company being able to run the API if they scan his user/pwd.

**Comment by veewee** [comment]
That is perfectly possible and looks like a great way of securing your API :)

**Comment by grosch** [comment]
OK, one last question (I think...).  I'm trying to use this now with Alamofire's authentication and that seems to want me to give it a .cer file.  How do I take the client files we generated and make a .cer out of it that I can bundle with my app?

**Comment by grosch** [comment]
Actually, I think I'd prefer it in DER format.

**Comment by veewee** [comment]
Hello @grosch,

The PEM file contains both the certificate and a private key.
You can extract the certificate in DER format with following commang IIRC:

```
openssl x509 -inform PEM -in client.pem -outform DER -out client-certificate.cer
```

**Comment by grosch** [comment]
Thanks much.  I think I'm good to go now....except Alamofire doesn't support this :(

I've got an enhancement request into them to support the certificate natively.  Please close out this issue and again, thanks for all the help!

**Comment by veewee** [comment]
No problem!
I'll try to update the article soon to make it easier for other people to find their way :)
