### ISSUE TITLE
phpro soap-client

### ISSUE THREAD

**Issue by tknuppe** [veewee/veewee.github.io#5]
Hi Toon
I'm using the phpro/soap-client and until today I was very happy with it. Today two things came up that are not handled out of the box.

1) I have a WSDL where Type-Extensions are used. I saw that someone has already added an ExtendAssembler which could be useful to workaround this. But it is only in the dev-master. So I ask myself and you if the dev-master is stable enough to use it for production. Otherwise would you mind to release a new stable version (0.5.3) ASAP?

2) Also in the same API description there are Arrays used (sequences). I guess it will be okay when I use the IteratorAssembler in this case but I'm not quite sure. Am I right with my assumption?

Regards
Thomas

**Comment by veewee** [comment]
Hi @tknuppe,

Can you please ask your questions in the official project issue tracker? This way we can keep track on the questions and spread the questions among different people in our organization.

Thanks for your understanding.
