### ISSUE TITLE
PHPro/SOAP

### ISSUE THREAD

**Issue by devsimo** [veewee/veewee.github.io#9]
Hi,

I have to develop a SOAP client and i want to use your library (phpro/soap) for this.

Can you please share with a simple example that shows how to pass the header and body to a SOAP request, below the exemple:

<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:loc="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local">
    <soapenv:Header>
        <tns:RequestSOAPHeader
            xmlns:tns="http://www.hu.com/schema/common/v2_1">
            <tns:spId>35000001</tns:spId>
            <tns:timeStamp>20080101010101</tns:timeStamp>
        </tns:RequestSOAPHeader>
    </soapenv:Header>
    <soapenv:Body>
        <loc:subscribeProductRequest>
            <loc:subscribeProductReq>
                <userID>
                    <ID>8612312312123</ID>
                    <type>0</type>
                </userID>
            </loc:subscribeProductReq>
        </loc:subscribeProductRequest>
    </soapenv:Body>
</soapenv:Envelope>

Thanks for your help!

Best Regards.

**Comment by veewee** [comment]
Hello @devsimo,

This is just my blog repository. Feel free to open up a support issue in the correct repository.
It's best if you add some more information about what you already have and what you want to accomplish exactly. Currently that is not clear from the information above.

**Comment by devsimo** [comment]
Hello @veewee 

OK it's noted.

Thanks,
Best Regards.
